- name: Install web server on Centos
  ansible.builtin.yum:
    name: "httpd"
    state: present
    
- name: Make sure a httpd is running
  ansible.builtin.systemd:
    state: started
    name: httpd
