- name: Install the correct web server for RHEL
  import_tasks: centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Copy web server public thml
  import_tasks: content.yml