- name: Install web server on Ubuntu
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: Make sure a apache2 is running
  ansible.builtin.systemd:
    state: started
    name: apache2
